[package]
name = "AftermathAmmExtensionDaoFee"
version = "1.0.0"
edition = "2024.beta"
license = "Apache 2.0"
authors = ["AftermathFinance", "github@aftermath.finance"]
published-at = "0x6f60a091637054e23915b8745c0c0d47b1d49618ee3435b5f68eccf6a44fb53d"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/mainnet" }
AftermathAmm = { local = "../../move-interfaces/packages/amm/amm" }
InsuranceFund = { local = "../../move-interfaces/packages/amm/amm-insurance-fund" } 
ReferralVault = { local = "../../move-interfaces/packages/amm/amm-referral-vault" }
Treasury = { local = "../../move-interfaces/packages/amm/amm-treasury" }
ProtocolFeeVault = { local = "../../move-interfaces/packages/amm/amm-protocol-fee-vault" }

[addresses]
amm_extension_dao_fee = "0x6f60a091637054e23915b8745c0c0d47b1d49618ee3435b5f68eccf6a44fb53d"
amm = "0xefe170ec0be4d762196bedecd7a065816576198a6527c99282a2551aaa7da38c"
insurance_fund = "0xa6baab1e668c7868991c1c3c11e144100f5734c407d020f72a01b9d1a8bcb97f"
referral_vault = "0xc66fabf1a9253e43c70f1cc02d40a1d18db183140ecaae2a3f58fa6b66c55acf"
treasury = "0x64213b0e4a52bac468d4ac3f140242f70714381653a1919a6d57cd49c628207a"
protocol_fee_vault = "0x2d9316f1f1a95f6d7c85a4e690ef7c359e6649773ef2c37ad7d9857adb6bef06"