[package]
name = "MemezLocks"
edition = "2024.beta" 
license = "MIT"           
authors = ["Jose Cerqueira (jose@interestprotocol.com)"]    

[dependencies]
InterestMath = { git = "https://github.com/interest-protocol/interest-math.git", rev = "main" }
TurbosCLMM = { local = "../dependencies/turbos" }
CetusClmm = { local = "../dependencies/cetus_clmm" }

[addresses]
memez_locks = "0x00987"
cetus_clmm = "0x75b2e9ecad34944b8d0c874e568c90db0cf9437f0d7392abfd4cb902972f3e40" 
turbos_clmm = "0x91bfbc386a41afcfd9b2533058d7e915a1d3829089cc268ff4333d54d6339ca1" 