[package]
name = "MemezLocks"
edition = "2024.beta" 
license = "MIT"           
authors = ["Jose Cerqueira (jose@interestprotocol.com)"]    

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/mainnet", override = true }
InterestMath = { git = "https://github.com/interest-protocol/interest-math.git", rev = "main" }
MemezACL = { local = "../acl" }
MemezFees = { local = "../fees" }
TurbosCLMM = { local = "../dependencies/turbos" }
CetusClmm = { local = "../dependencies/cetus" }

[addresses]
memez_locks = "0x00987"
sui = "0x2"
cetus_clmm = "0x1eabed72c53feb3805120a081dc15963c204dc8d091542592abaf7a35689b2fb" 
turbos_clmm = "0x91bfbc386a41afcfd9b2533058d7e915a1d3829089cc268ff4333d54d6339ca1" 

