[package]
name = "IPXCoinStandard"
edition = "2024.beta"
license = "MIT"          
authors = ["Jose Cerqueira (jose@interestprotocol.com)"] 
published-at = "0x03979c0d3fac9c7cd89bc3b0b8de0aff4f23369be980b789b06c1b104f90eff3"

[dependencies]

[addresses]
ipx_coin_standard = "0x03979c0d3fac9c7cd89bc3b0b8de0aff4f23369be980b789b06c1b104f90eff3"