[package]
name = "XPumpMigrator"
edition = "2024.beta" 
license = "MIT"          
authors = ["Jose Cerqueira (jose@interestprotocol.com)"]     

[dependencies]
ipx_coin_standard = { r.mvr = "@interest/coin-standard" }
MemezFun = { local = "../../fun" }
BluefinSpot = { git = "https://github.com/fireflyprotocol/bluefin-spot-contract-interface.git", rev = "main" }

[addresses]
xpump_migrator = "0x0"
treasury = "0x5b2aec3521419fe055b6753b15cbad845ec1dca852b75ad0b13b569f2329f82d"

[r.mvr]
network = "mainnet"