[package]
name = "recrd"
edition = "2024.beta" 
license = "MIT"          
authors = ["Jose Cerqueira (jose@interestprotocol.com)"]     


[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/mainnet", override = true }
IPXCoinStandard = { git = "https://github.com/interest-protocol/ipx-coin-standard.git", rev = "main" }

MemezACL = { local = "../../acl" }
MemezFun = { local = "../../fun" }
CetusClmm = { local = "../../dependencies/cetus_clmm" }

[addresses]
recrd = "0x0"
cetus_clmm = "0x1eabed72c53feb3805120a081dc15963c204dc8d091542592abaf7a35689b2fb"
treasury = "0x0"