[package]
name = "RecrdMigrator"
edition = "2024.beta" 
license = "MIT"          
authors = ["Jose Cerqueira (jose@interestprotocol.com)"]     


[dependencies]
ipx_coin_standard = { r.mvr = "@interest/coin-standard" }
CetusClmm = { git = "https://github.com/CetusProtocol/cetus-clmm-interface.git", subdir = "sui/cetus_clmm", rev = "mainnet-v1.49.2" }

MemezFun = { local = "../../fun" }

[addresses]
recrd_migrator = "0x0"
cetus_clmm = "0x75b2e9ecad34944b8d0c874e568c90db0cf9437f0d7392abfd4cb902972f3e40"
treasury = "0x0"

[r.mvr]
network = "mainnet"