[package]
name = "RecrdMigrator"
edition = "2024.beta" 
license = "MIT"          
authors = ["Jose Cerqueira (jose@interestprotocol.com)"]     


[dependencies]
ipx_coin_standard = { r.mvr = "@interest/coin-standard" }

MemezFun = { local = "../../fun" }
CetusClmm = { local = "../../dependencies/cetus_clmm" }

[addresses]
recrd_migrator = "0x0"
cetus_clmm = "0x1eabed72c53feb3805120a081dc15963c204dc8d091542592abaf7a35689b2fb"
treasury = "0x0"

[r.mvr]
network = "mainnet"