[package]
name = "LpBurn"
version = "1.2.0"
edition = "2024.beta" # edition = "legacy" to use legacy (pre-2024) Move
published-at = "0xf80a6bb02d98cebf90a6476e8c106a4ddf1865ef79d6067a66933eb57b9f0f7b"

[dependencies]
CetusClmm = { local = "../cetus_clmm" }
ClmmVester = { local = "../clmm_vester" }

[addresses]
lpburn = "0x12d73de9a6bc3cb658ec9dc0fe7de2662be1cea5c76c092fcc3606048cdbac27"

[r.mvr]
network = "mainnet"
