[package]
name = "MemezFun"
edition = "2024.beta" 
license = "Apache-2.0"           
authors = ["Jose Cerqueira (jose@interestprotocol.com)"]   

[dependencies]

Memez = { local = "../memez" }
MemezVesting = { local = "../vesting" }

interest_bps = { r.mvr = "@interest/bps" }
interest_math = { r.mvr = "@interest/math" }
interest_access_control = { r.mvr = "@interest/acl" }
interest_constant_product = { r.mvr = "@interest/constant-product" }
ipx_coin_standard = { r.mvr = "@interest/coin-standard" }

[addresses]
memez_fun = "0x0"

[r.mvr]
network = "mainnet"
