[package]
name = "MemezFun"
edition = "2024.beta" 
license = "MIT"           
authors = ["Jose Cerqueira (jose@interestprotocol.com)"]   

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/mainnet" }

InterestBPS = { git = "https://github.com/interest-protocol/bps.git", rev = "main" }
InterestMath = { git = "https://github.com/interest-protocol/interest-math.git", rev = "main" }
IPXCoinStandard = { git = "https://github.com/interest-protocol/ipx-coin-standard.git", rev = "main" }
ConstantProduct = { git  = "https://github.com/interest-protocol/constant-product.git", rev = "main" }

MemezACL = { local = "../acl" }
MemezVesting = { local = "../vesting" }

[addresses]
memez_fun = "0x0123456789abcdef"