[package]
name = "NexaMigrator"
edition = "2024.beta" # edition = "legacy" to use legacy (pre-2024) Move
license = "MIT"          
authors = ["Jose Cerqueira (jose@interestprotocol.com)"]   

[dependencies]
IPXCoinStandard = { git = "https://github.com/interest-protocol/ipx-coin-standard.git", rev = "main", override = true }

MemezFun = { local = "../../fun" }
BluefinSpot = { local = "../../dependencies/bluefin" }

[addresses]
nexa_migrator = "0x0"
treasury = "0x1"
