[package]
name = "memez_profile"
edition = "2024.beta"
license = "Apache-2.0"           
authors = ["Jose Cerqueira (jose@interestprotocol.com)"]   

[dependencies]
MemezFun = { local = "../../fun" }

[addresses]
memez_profile = "0x0"
