name: Memez CI

on:
    pull_request:

env:
    MOVE_PACKAGES_PATH: .

jobs:
    test-move-packages:
        name: Test Move Packages
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ${{ env.MOVE_PACKAGES_PATH }}
        steps:
            - uses: actions/checkout@v2
            - name: Download MVR
              uses: jaxxstorm/action-install-gh-release@v1.12.0
              with:
                  repo: MystenLabs/mvr
                  extension-matching: disable
                  rename-to: mvr
                  platform: ubuntu
                  cache: enable
                  chmod: 0755
            - run: mvr search @potatoes
            - name: Download Sui
              uses: jaxxstorm/action-install-gh-release@v1.12.0
              with:
                  repo: MystenLabs/sui
                  platform: ubuntu
                  cache: enable
            # # List all directories in the packages folder, and run sui move test on
            # # each of them
            - run: ls -d ./*/ | xargs -I {} bash -c "sui move test --path '{}'"

    move-formatter:
        name: Check Move formatting
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: MystenLabs/move-formatter-action@v1
              with:
                  working-directory: ${{ env.MOVE_PACKAGES_PATH }}
