# Run unit tests against sui testnet

name: Run Sui Move Tests

on:
    pull_request:
    push:
        branches: [main]

jobs:
    move-test:
        runs-on: ubuntu-latest
        container:
            image: mysten/sui-tools:testnet
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Install git
              run: apt-get install -y git

            - name: Run memez.gg tests
              run: sui move test -p ./fun && sui move test -p ./locks && sui move test -p ./vesting && sui move test -p ./otc
